let Joi,CustomErrorHandler,User;_355‍.x([["default",()=>_355‍.o]]);_355‍.w("joi",[["default",["Joi"],function(v){Joi=v}]]);_355‍.w("../../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);_355‍.w("../../models",[["User",["User"],function(v){User=v}]]);



const registerController = {
  async register(req, res, next) {
    // Validation Schema
    const registerSchema = Joi.object({ 
      name: Joi.string().min(3).max(30).required(),
      email: Joi.string().email().required(),
      password: Joi.string()
        .pattern(new RegExp("^[a-zA-Z0-9]{3,30}$"))
        .required(),
      repeat_password: Joi.ref("password"),
    });
    // End of Validation Schema

    const {error} = registerSchema.validate(req.body);
    if (error) {
      return next(error);
    }

    // Check if user is exists

    try {
      const exist = await User.exists({email: req.body.email});
      if (exist) {
        return next(
          CustomErrorHandler.alreadyExist("This email is already taken.")
        );
      }
    } catch (err) {
      return next(err);
    } 

    res.send({
      message: "OK",
      data: req.body,
    });
  },
};

_355‍.d(registerController);
